# Generated by Django 5.2.6 on 2025-09-17 21:23

import apartments.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lat', models.FloatField(editable=False, null=True)),
                ('lon', models.FloatField(editable=False, null=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='accounts.profile')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='universities.university')),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apartments.models.apartment_image_upload_path, validators=[apartments.models.validate_image])),
                ('caption', models.CharField(blank=True, max_length=120)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='apartments.apartment')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
                ('is_vacant', models.BooleanField(default=True)),
                ('room_type', models.CharField(choices=[('single', 'Single'), ('bedsitter', 'Bedsitter'), ('onebedroom', 'One Bedroom'), ('twobedroom', 'Two Bedroom')], default='single', max_length=20)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='apartments.apartment')),
            ],
        ),
        migrations.CreateModel(
            name='RoomVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('single', 'Single'), ('bedsitter', 'Bedsitter'), ('onebedroom', 'One Bedroom'), ('twobedroom', 'Two Bedroom')], max_length=20)),
                ('video', models.FileField(upload_to=apartments.models.room_video_upload_path, validators=[apartments.models.validate_video])),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='apartments.apartment')),
            ],
            options={
                'unique_together': {('apartment', 'room_type')},
            },
        ),
    ]
