# Generated by Django 5.2.6 on 2025-10-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_alter_apartmentimage_apartment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='monthly_rent',
        ),
        migrations.AddField(
            model_name='room',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
